export const morningMessages = {
working: [
"You are stepping into another day of effort and strength.",
"Another working day begins. Move steadily.",
"Your work matters even when no one notices.",
"Today is another page in the life you are building.",
"You do not need to be perfect today.",
"Quiet effort changes the future.",
"Your consistency is powerful.",
"Move through the day one task at a time.",
"The world runs on people who keep showing up.",
"Today your strength is quiet persistence.",
"You are capable of handling today.",
"Take the morning slowly and begin.",
"Your effort is building something real.",
"The day ahead is manageable step by step.",
"You have handled difficult days before.",
"Focus on the next small action.",
"Today your patience will carry you forward.",
"Another working day, another opportunity to grow.",
"You are stronger than your stress.",
"The day begins with calm intention.",
"Your presence at work matters.",
"Move gently but keep moving.",
"Today is about steady progress.",
"Let your mind stay calm while you work.",
"You are allowed to take things slowly.",
"Small wins today still count.",
"You do not have to rush the day.",
"Work is simply effort spread across time.",
"One task at a time is enough.",
"Your discipline is a quiet superpower.",
"You have made it through many days already.",
"The morning holds possibility.",
"You bring value just by showing up.",
"Progress is built quietly.",
"You deserve patience with yourself today.",
"Today is another step forward.",
"Your work contributes to the world.",
"Let calm guide your work.",
"The day will unfold naturally.",
"You are capable of today's challenges.",
"Trust your ability to figure things out.",
"Your focus will carry you through.",
"You can handle what today brings.",
"Let the morning settle your mind.",
"Consistency beats perfection.",
"You have the strength for today.",
"Work can be done calmly.",
"Your effort today matters.",
"You are building resilience.",
"The day does not need to be overwhelming.",
"Every working day builds experience.",
"You are capable of learning anything required today.",
"Stay steady and patient.",
"Work becomes easier when taken slowly.",
"Your determination is real.",
"Focus on what you can control.",
"You bring your own quiet power to work.",
"Today can move at your pace.",
"Your growth is happening quietly.",
"Another opportunity to show your strength.",
"You deserve respect for your effort.",
"Keep your mind calm and focused.",
"Work becomes manageable step by step.",
"You are capable and prepared.",
"The day belongs to your steady effort.",
"Trust your skills.",
"You are building a life through your work.",
"Your persistence is admirable.",
"Stay grounded today.",
"Progress does not need to be loud.",
"You are doing better than you think.",
"The workday is simply a journey of small tasks.",
"Today will pass just like the others.",
"You are learning and improving.",
"Your effort is shaping your future.",
"Confidence grows through action.",
"Stay calm and continue.",
"You have everything needed for today.",
"Work becomes lighter when taken slowly.",
"Your focus is powerful.",
"You deserve pride in your work.",
"Take a deep breath and begin.",
"You are capable of solving problems.",
"Every day you grow stronger.",
"The day may challenge you but you can meet it.",
"You have the ability to adapt.",
"Trust the process of your work.",
"Keep your mind steady.",
"You are building experience every day.",
"Work becomes easier with patience.",
"You can move through today with calm.",
"Your effort is meaningful.",
"You have already overcome much.",
"Today is another opportunity to grow.",
"Step forward with confidence.",
"You are capable of managing the day.",
"Strength appears through persistence.",
"Trust your ability to learn.",
"Your work contributes to your independence.",
"You are stronger than the stress of work.",
"Today begins with courage."
],

dayoff: [
"Today belongs to you.",
"A day off is a day your mind can breathe.",
"Rest is not laziness. It is repair.",
"You earned this quiet day.",
"Let today move slowly.",
"The world can wait while you rest.",
"Today does not require productivity.",
"Take the day gently.",
"Your mind deserves a pause.",
"Nothing urgent needs your energy today.",
"A day off is space to exist freely.",
"Let yourself slow down.",
"Today is for recovery.",
"Rest is a powerful act.",
"Enjoy the quiet rhythm of today.",
"Give yourself permission to do less.",
"Peace grows in slow moments.",
"The day is yours to shape.",
"Let calm guide your day.",
"Your body deserves rest.",
"You do not need to rush today.",
"A quiet day is valuable.",
"Today can unfold naturally.",
"Let your thoughts wander freely.",
"Today is not about achievement.",
"You are allowed to simply exist today.",
"Move through the day softly.",
"Let rest restore your strength.",
"Today belongs to your wellbeing.",
"You deserve a peaceful day.",
"Slow mornings are a gift.",
"Today is for gentle living.",
"Let your mind drift without pressure.",
"You are allowed to relax.",
"Take today one peaceful moment at a time.",
"Today can be light.",
"Your energy deserves renewal.",
"A day off is a reset for the mind.",
"Let your breathing slow today.",
"Enjoy small quiet moments.",
"Today does not need structure.",
"Your mind can rest today.",
"Give your thoughts space.",
"Rest is part of a healthy life.",
"Today is a pause in the rhythm of work.",
"Enjoy the calm of today.",
"Let your body recover.",
"A slow day can heal tired thoughts.",
"You deserve time for yourself.",
"Let the day unfold gently.",
"Today is about comfort.",
"You have permission to relax.",
"A calm day strengthens tomorrow.",
"Enjoy doing things slowly.",
"The day asks nothing from you.",
"Rest makes tomorrow easier.",
"Today is your personal space.",
"Let your mind breathe deeply.",
"Quiet days are powerful.",
"You deserve moments of peace.",
"The world can move without you today.",
"Allow yourself to recharge.",
"Take the day as it comes.",
"Let the silence feel good.",
"You deserve softness today.",
"A day off restores balance.",
"Resting is productive for your mind.",
"Today is for calm living.",
"Your wellbeing matters today.",
"Enjoy the stillness.",
"Let today be simple.",
"A peaceful day has great value.",
"You do not need to prove anything today.",
"Today is about caring for yourself.",
"Let your mind rest completely.",
"Take time for things that feel good.",
"The day belongs to your comfort.",
"Rest renews strength.",
"Enjoy the freedom of today.",
"Let the hours pass gently.",
"You deserve quiet happiness.",
"Today is not about pressure.",
"Let calm fill your day.",
"Your mind deserves a break.",
"Today you can move at your own pace.",
"Relaxation is part of balance.",
"Let the day feel spacious.",
"You deserve this rest.",
"Take the day slowly and peacefully.",
"Let your thoughts settle.",
"A calm day helps the mind reset.",
"Your body and mind deserve care.",
"Enjoy the freedom of not rushing.",
"Today is your breathing space.",
"Peace begins with rest.",
"Let the day feel easy.",
"You deserve a gentle day.",
"Rest builds tomorrow's strength.",
"Take time to simply enjoy being alive."
],

overwhelmed: [
"Breathe first. Everything else can wait a moment.",
"You do not have to solve everything today.",
"Take one small step. That is enough.",
"It is okay to feel overwhelmed sometimes.",
"The day can be handled piece by piece.",
"You are not alone in feeling this way.",
"Slow your breathing and begin again.",
"Everything does not need your attention at once.",
"Start with the smallest task.",
"You are capable of moving through this moment.",
"Pause for a breath before continuing.",
"Your mind deserves patience today.",
"Overwhelm is a signal to slow down.",
"Take the day in smaller pieces.",
"You only need to handle the next step.",
"The world can wait while you breathe.",
"You are stronger than this moment of stress.",
"Give your thoughts space to settle.",
"Let the pressure loosen a little.",
"You do not have to rush today.",
"Step back and breathe.",
"The day can unfold slowly.",
"Focus on one thing at a time.",
"Your effort is enough today.",
"Be kind to yourself in this moment.",
"Overwhelming days eventually pass.",
"Let the mind calm down first.",
"You can take things slowly.",
"It is okay to ask for help if needed.",
"Your feelings are valid.",
"Start where you are.",
"You are doing the best you can.",
"One step is enough right now.",
"Pause before the next action.",
"You do not have to carry everything alone.",
"Let yourself breathe deeply.",
"Today can move slowly.",
"The mind settles with patience.",
"You are allowed to take breaks.",
"Handle only what is necessary first.",
"The pressure does not define you.",
"You can move through this moment.",
"Focus on what is in front of you.",
"You have survived difficult days before.",
"Take another calm breath.",
"You do not have to be perfect today.",
"Give your mind some room.",
"Stress does not last forever.",
"Move gently through the day.",
"You are stronger than you think.",
"Let your thoughts slow down.",
"Small progress still counts.",
"The moment will pass.",
"You can manage the next step.",
"Everything will not stay this intense.",
"Your mind deserves compassion.",
"Take the day one moment at a time.",
"Pause whenever you need.",
"Even slow progress is progress.",
"You are allowed to feel overwhelmed.",
"Handle only what you can right now.",
"Your breath can guide you back to calm.",
"You are not failing. You are human.",
"Let yourself reset.",
"The day can still be handled calmly.",
"Take one problem at a time.",
"You do not need to rush solutions.",
"Your presence is enough right now.",
"Focus on the next simple action.",
"You are capable of finding balance again.",
"Let calm slowly return.",
"One small decision at a time.",
"You can regain control step by step.",
"Your strength grows through patience.",
"The pressure will ease.",
"Your mind deserves gentleness.",
"You can slow down and think clearly.",
"You have the ability to adapt.",
"Start with the easiest thing.",
"Your effort still matters.",
"Give yourself a moment of stillness.",
"You can move forward calmly.",
"The day will not defeat you.",
"Trust your ability to handle things gradually.",
"Let the storm of thoughts pass.",
"Take a moment for yourself.",
"You can find clarity again.",
"Your mind will settle.",
"You deserve patience today.",
"Even difficult days pass eventually.",
"You have the strength to continue.",
"Take your time with everything.",
"The pressure will fade.",
"You can handle one step right now.",
"Give your mind the space it needs.",
"You are capable of regaining calm.",
"Let your breath guide you back.",
"Everything does not need solving today.",
"You are stronger than this stress.",
"The moment will pass and you will continue."
],

calm: [
"Carry this calm with you into the day.",
"A peaceful mind makes the day lighter.",
"Let today's calm guide your actions.",
"Move through the day with steady clarity.",
"This calm is your quiet strength.",
"Let the day unfold gently.",
"A calm start can shape the entire day.",
"Hold on to this peaceful moment.",
"Today begins with quiet confidence.",
"A calm mind solves problems easily.",
"Let patience guide your work today.",
"This calm is a good foundation for the day.",
"Move steadily and thoughtfully.",
"Peaceful beginnings create balanced days.",
"Let calm lead the way forward.",
"Today can move at a gentle pace.",
"A clear mind sees clearly.",
"Let your calm energy shape the day.",
"Today begins with balance.",
"Your calm presence is powerful.",
"Let the day grow naturally.",
"Carry this quiet focus with you.",
"A steady mind moves through challenges easily.",
"Let calm shape your decisions.",
"Peaceful mornings bring productive days.",
"Move slowly and confidently.",
"Let your calm become strength.",
"Today is another balanced step forward.",
"A relaxed mind sees opportunities.",
"Let clarity guide you.",
"Today begins with quiet power.",
"Stay grounded throughout the day.",
"Calm thinking leads to wise choices.",
"Let the day move naturally around you.",
"Peaceful thoughts build steady progress.",
"Move through the day with grace.",
"A calm mind is a strong mind.",
"Today can remain balanced.",
"Let your steady energy guide you.",
"Peace can stay with you today.",
"Your calm focus is valuable.",
"Let your thoughts remain clear.",
"Move through work with ease.",
"Calm moments create strong days.",
"Stay grounded and steady.",
"Let calm guide your productivity.",
"The day is easier with a peaceful mind.",
"Carry this calm into every task.",
"A balanced mind handles anything.",
"Let today remain gentle.",
"Peace grows with patience.",
"Move through the day with quiet strength.",
"Today begins with stability.",
"Let calm shape your interactions.",
"Your steady presence matters.",
"Today can stay peaceful.",
"Trust the calm inside you.",
"Let clarity guide your work.",
"A peaceful mind makes wise decisions.",
"Stay centered throughout the day.",
"Let calm guide every step.",
"Peaceful beginnings lead to balanced endings.",
"Carry your calm forward.",
"A steady start builds a strong day.",
"Move through the hours with ease.",
"Your calm energy influences the world around you.",
"Let the day remain smooth.",
"Stay relaxed while moving forward.",
"Peace can remain even in busy moments.",
"Let calm guide your focus.",
"A balanced mind stays resilient.",
"Carry calm into each moment.",
"Your calm awareness is powerful.",
"Move through the day with quiet assurance.",
"Let the calm morning stay with you.",
"A steady heart handles anything.",
"Let today feel balanced.",
"Peace grows through mindful moments.",
"Move through tasks with clarity.",
"Your calm presence helps others too.",
"Let your mind stay light today.",
"A calm day begins with calm thoughts.",
"Stay centered and steady.",
"Let peace guide your actions.",
"Your calm focus creates good work.",
"Today begins with quiet confidence.",
"Carry your calm into the world.",
"A peaceful mind sees solutions.",
"Stay grounded through the day.",
"Let calm become your strength.",
"Today can remain smooth and steady.",
"Move with patience and clarity.",
"Peaceful thinking supports strong decisions.",
"Stay relaxed while working.",
"Let calm stay with you all day.",
"Today starts with balance and strength.",
"A calm morning leads to a calm life."
],

period: {
day1: [
"Your body is working hard today. Be gentle with it.",
"Today asks for softness and patience.",
"You are allowed to slow down today.",
"Rest whenever your body asks for it.",
"Your body deserves kindness today.",
"Move gently through the day.",
"Today is about listening to your body.",
"Take the day slowly.",
"Your strength includes resting.",
"You do not have to push yourself today.",
"Your body is resetting. Let it.",
"Comfort matters today.",
"You deserve extra care today.",
"Let yourself move slowly.",
"Today may feel heavy and that is okay.",
"Be patient with your energy.",
"Your body is doing important work.",
"Rest is a form of strength today.",
"You are allowed to take breaks.",
"Listen to what your body needs.",
"Today is about care, not pressure.",
"Give yourself permission to slow down.",
"You deserve comfort today.",
"Your body is going through a natural cycle.",
"Move at the pace your body chooses.",
"Take small steps today.",
"Kindness toward yourself matters today.",
"You are allowed to feel tired.",
"Rest when you need it.",
"Your wellbeing matters today.",
"Today is a softer day.",
"Let your body guide your pace.",
"You deserve patience today.",
"Take gentle care of yourself.",
"Nothing today needs rushing.",
"Your body is worthy of compassion.",
"Allow yourself extra rest.",
"Today is about healing and balance.",
"Move through the day calmly.",
"You are not weak for needing rest.",
"Give your body space today.",
"You deserve understanding today.",
"Take the day moment by moment.",
"Your body is doing its work.",
"Let yourself be comfortable today.",
"Energy may be low and that is normal.",
"You are allowed to move slowly.",
"Care for your body kindly.",
"Your comfort is important today.",
"Take time to breathe deeply.",
"Be gentle with yourself.",
"Today can be quiet and calm.",
"You deserve extra patience today.",
"Listen to your body's signals.",
"Move gently through each moment.",
"Your body is working hard.",
"Today asks for calm.",
"Give yourself grace today.",
"You deserve warmth and rest.",
"Your body deserves kindness.",
"Take everything slowly.",
"Today can be softer.",
"Rest when your body asks.",
"You deserve gentle treatment.",
"Nothing today must be rushed.",
"Care for yourself with patience.",
"Your body is doing natural work.",
"Move slowly and comfortably.",
"You are allowed to pause.",
"Your body deserves attention today.",
"Take small breaks when needed.",
"Comfort comes first today.",
"You deserve softness today.",
"Your strength includes rest.",
"Take the day gently.",
"Your body is not asking too much.",
"You deserve peace today.",
"Move through the day slowly.",
"Take care of yourself first.",
"Your body deserves respect.",
"Today can be quiet.",
"You are allowed to take it easy.",
"Listen carefully to your body.",
"Your comfort matters.",
"Move with patience.",
"Take time for yourself.",
"Your body deserves compassion.",
"Today is about healing.",
"You deserve gentleness.",
"Rest when needed.",
"Take today calmly.",
"Be kind to your body.",
"You deserve softness today.",
"Move slowly and carefully.",
"Your body knows what it needs.",
"Take things gently today.",
"You deserve care and patience.",
"Rest and breathe today."
],
day2: [
"Your body is still working hard today. Move gently.",
"Take the day slowly and listen to your body.",
"You deserve patience today.",
"Energy may still feel low and that is normal.",
"Give yourself the space to move calmly today.",
"Your body is continuing its reset.",
"Rest whenever your body asks for it.",
"Today can move at a gentle pace.",
"Your strength includes caring for yourself.",
"Take small steps through the day.",
"You deserve comfort and patience today.",
"Let your body guide the rhythm of your day.",
"Move gently and breathe deeply.",
"You are allowed to take breaks today.",
"Your wellbeing matters more than productivity.",
"Listen to your body carefully today.",
"Today is about balance and patience.",
"You deserve softness today.",
"Take moments to rest when needed.",
"Your body is still adjusting.",
"Move through the day calmly.",
"You do not have to rush anything today.",
"Your body deserves kindness.",
"Take care of yourself first today.",
"You are allowed to slow down.",
"Your energy will return gradually.",
"Let today unfold gently.",
"Take the day one moment at a time.",
"Your body knows what it needs.",
"Give yourself compassion today.",
"You deserve extra care.",
"Move through the day with patience.",
"Take quiet breaks when you need them.",
"Your comfort matters today.",
"Rest is part of healing.",
"You are allowed to take things slowly.",
"Your body deserves attention today.",
"Today is another step in your body's cycle.",
"Be gentle with your expectations today.",
"You deserve calm and patience.",
"Take a slow breath and continue.",
"Move at your body's pace.",
"Today can be softer than usual.",
"Your strength includes listening to your body.",
"Take gentle care of yourself today.",
"You deserve understanding.",
"Nothing today needs rushing.",
"Let the day remain calm.",
"Your body is doing important work.",
"Take everything slowly.",
"You deserve kindness today.",
"Let comfort guide your choices today.",
"Move through the day carefully.",
"Take breaks without guilt.",
"Your body deserves patience.",
"You are allowed to move slowly.",
"Today can remain gentle.",
"Your body is still finding balance.",
"Give yourself grace today.",
"You deserve peace and rest.",
"Move softly through the hours.",
"Your body deserves compassion.",
"Take time to relax when needed.",
"You deserve a calm day.",
"Let your body lead today.",
"Take the day step by step.",
"Your comfort is important.",
"You deserve patience and care.",
"Rest when your body asks for it.",
"Move through today gently.",
"You deserve understanding today.",
"Take everything at your own pace.",
"Your body is still resetting.",
"You deserve softness today.",
"Take moments of quiet when possible.",
"Let the day stay gentle.",
"Your body deserves kindness and care.",
"Move through the day slowly.",
"You deserve comfort and patience.",
"Take care of yourself today.",
"Your body is guiding you.",
"Give yourself the time you need.",
"You deserve calm today.",
"Let the day move softly.",
"Your wellbeing comes first.",
"Take a deep breath and move slowly.",
"You deserve patience today.",
"Move gently through the day.",
"Your body deserves respect.",
"Take the day calmly.",
"You deserve rest and care.",
"Let yourself slow down.",
"Your body is doing its work.",
"Take gentle care of yourself today.",
"You deserve understanding.",
"Move slowly and patiently.",
"Your comfort matters today.",
"Rest when you need it.",
"You deserve a peaceful day."
],
day3: [
"Your body is continuing its cycle with strength.",
"Move gently but trust your energy today.",
"You are finding your balance again.",
"Today may feel steadier than yesterday.",
"Let your body guide your pace.",
"You are doing well listening to your body.",
"Move calmly through the day.",
"Your strength is quiet and steady today.",
"Trust the rhythm of your body.",
"You deserve patience and care.",
"Your body continues its natural reset.",
"Move through the day with gentleness.",
"You are finding your rhythm again.",
"Today can move calmly.",
"Your body deserves appreciation.",
"Take the day at a steady pace.",
"Your strength is returning gradually.",
"Move forward with patience.",
"Your body knows its rhythm.",
"Today can feel more balanced.",
"You deserve calm and kindness.",
"Let your body guide the day.",
"Your resilience shows quietly today.",
"Move steadily and comfortably.",
"Your body is adjusting naturally.",
"You are doing enough today.",
"Take the day slowly but confidently.",
"Your balance is returning.",
"You deserve care and patience.",
"Move gently through the day.",
"Your body continues its work.",
"Today can feel calmer.",
"You deserve comfort and stability.",
"Let your energy guide you.",
"Your body is moving through its cycle well.",
"Take things one step at a time.",
"You deserve peace today.",
"Move through the hours calmly.",
"Your strength is steady today.",
"Your body is returning to balance.",
"You deserve patience and care.",
"Trust your body's process.",
"Move through the day gently.",
"You are doing well listening to yourself.",
"Today may feel a little lighter.",
"Your body deserves kindness.",
"Take the day calmly.",
"You deserve softness today.",
"Move forward gently.",
"Your body continues its cycle naturally.",
"You are moving through this with strength.",
"Take the day steadily.",
"You deserve comfort today.",
"Your balance is improving.",
"Move calmly through the day.",
"Your body deserves respect.",
"Let your body guide the pace.",
"You deserve understanding.",
"Today can feel smoother.",
"Your energy may return slowly.",
"Move steadily and gently.",
"Your body continues its reset.",
"You deserve care today.",
"Take time to breathe deeply.",
"Your body deserves patience.",
"Move forward with calm energy.",
"You deserve peace and comfort.",
"Your strength is steady today.",
"Let the day unfold naturally.",
"You are doing well today.",
"Your body continues its rhythm.",
"Take the day one step at a time.",
"You deserve calm moments.",
"Move through the day patiently.",
"Your body deserves compassion.",
"You are regaining balance.",
"Today may feel steadier.",
"You deserve kindness.",
"Your body is adjusting well.",
"Move gently and confidently.",
"You deserve calm today.",
"Your strength is returning.",
"Take the day slowly.",
"Your body continues its cycle naturally.",
"You deserve patience and understanding.",
"Move calmly through the day.",
"Your body deserves care.",
"You are finding balance again.",
"Take moments to breathe.",
"You deserve softness today.",
"Your energy may return gradually.",
"Move through the day with patience.",
"Your body deserves respect.",
"You are moving through this well.",
"Take the day calmly.",
"Your balance is returning today.",
"You deserve care and gentleness.",
"Move steadily and comfortably."
],
day4: [
"Your body is beginning to feel steadier today.",
"Energy may slowly return today.",
"You are moving into a calmer phase.",
"Today may feel lighter than the previous days.",
"Your body is restoring its balance.",
"Move through today with calm confidence.",
"Your strength is quietly returning.",
"Today can feel more comfortable.",
"Your body deserves appreciation for what it has done.",
"Let your energy return naturally.",
"You are moving forward in your cycle.",
"Today may feel more stable.",
"Your body continues its quiet recovery.",
"Move gently but trust your energy today.",
"You deserve patience and kindness today.",
"The hardest days may be behind you.",
"Let your body guide your pace.",
"You may notice your strength returning.",
"Today is a step toward balance.",
"Your body is restoring itself.",
"Move steadily through the day.",
"You deserve comfort and calm.",
"Your energy may slowly increase today.",
"Trust your body’s recovery.",
"Today can feel more manageable.",
"Your body deserves appreciation today.",
"You are moving toward balance again.",
"Take the day calmly and confidently.",
"Your strength continues to grow.",
"The cycle is moving forward.",
"You may feel steadier today.",
"Your body is regaining its rhythm.",
"Move through today gently.",
"You deserve peace today.",
"Your energy may begin returning.",
"Let the day unfold naturally.",
"Your body is recovering well.",
"You are moving into a lighter phase.",
"Take the day at a comfortable pace.",
"Your body deserves continued care.",
"Today may feel calmer.",
"You are regaining your balance.",
"Move through the day patiently.",
"Your strength is returning step by step.",
"Trust the rhythm of your body.",
"Today may feel smoother.",
"You deserve calm moments.",
"Your body is finding stability again.",
"Move steadily today.",
"You are moving toward renewed energy.",
"Let your body guide you gently.",
"Your cycle is progressing naturally.",
"Today may bring more comfort.",
"You deserve patience and kindness.",
"Your energy is gradually returning.",
"Move through the day calmly.",
"You are moving back toward balance.",
"Your body deserves respect and care.",
"Today can feel more manageable.",
"Let your strength grow naturally.",
"You may notice improved energy today.",
"Trust the recovery process.",
"Your body is restoring its normal rhythm.",
"Move gently and confidently.",
"You deserve comfort today.",
"The cycle continues forward.",
"You may feel steadier today.",
"Your body is regaining strength.",
"Take the day calmly.",
"Your energy is rebuilding.",
"Move with patience and balance.",
"Today may feel lighter.",
"Your body deserves appreciation.",
"You are moving into a calmer phase.",
"Trust the natural rhythm of your body.",
"Your energy may slowly rise today.",
"Move steadily through the day.",
"You deserve calm and comfort.",
"Your body is restoring balance.",
"Today can feel smoother.",
"You are moving forward in your cycle.",
"Take the day at your pace.",
"Your strength is returning quietly.",
"Let the day remain gentle.",
"Your body deserves continued care.",
"Today may feel easier.",
"You are regaining stability.",
"Move calmly and confidently.",
"Your body continues its recovery.",
"Energy may feel stronger today.",
"You deserve patience today.",
"Trust your body's process.",
"Your strength is rebuilding.",
"Move through the day comfortably.",
"Your body deserves kindness.",
"Today may feel more balanced.",
"You are moving toward renewed energy."
],
day5: [
"Your body is completing its cycle with strength.",
"Energy may begin returning more clearly today.",
"You are moving into a new phase of the cycle.",
"Your body has done important work this week.",
"Today may feel lighter than the previous days.",
"You are stepping into renewed balance.",
"Your strength is returning naturally.",
"The body is finishing its reset.",
"Let today unfold with gentle confidence.",
"You deserve appreciation for caring for yourself.",
"Your body is restoring its rhythm.",
"Today may bring a feeling of renewal.",
"You are moving toward fresh energy.",
"Your body has carried you through the cycle.",
"Move through today with calm strength.",
"Balance is returning steadily.",
"You deserve kindness and comfort today.",
"Your body is moving forward in its rhythm.",
"Today may feel more open and light.",
"You are stepping into renewed clarity.",
"Your strength continues to grow.",
"The cycle is completing its work.",
"Energy may return gradually today.",
"You deserve calm and confidence.",
"Your body is restoring itself beautifully.",
"Today may feel steadier and brighter.",
"You are moving into a new phase.",
"Your resilience shows quietly.",
"Let today feel fresh and balanced.",
"Your body deserves appreciation today.",
"You have moved through the hardest days.",
"Energy is slowly rising again.",
"You deserve a calm and comfortable day.",
"Your body is regaining its natural rhythm.",
"Today may bring a sense of renewal.",
"You are moving into stronger energy.",
"Your strength is returning quietly.",
"The cycle is nearing completion.",
"You deserve patience and pride.",
"Your body has done powerful work.",
"Today may feel lighter and steadier.",
"You are entering a fresh phase.",
"Your body continues restoring balance.",
"Move through today with quiet confidence.",
"You deserve peace and comfort.",
"Energy can return naturally today.",
"Your strength continues building.",
"The body is completing its reset.",
"You deserve appreciation for your resilience.",
"Today may feel brighter.",
"You are moving toward renewed vitality.",
"Your body is finding balance again.",
"Let the day feel calm and refreshing.",
"You deserve to feel proud of your strength.",
"The cycle is finishing its work.",
"Your energy is gradually rising.",
"You are stepping into a new rhythm.",
"Your body deserves gratitude today.",
"Today may feel like a small reset.",
"You have moved through the cycle with strength.",
"Energy and clarity may begin returning.",
"You deserve comfort and calm.",
"Your resilience is real.",
"The body is completing its renewal.",
"You are moving toward stronger days.",
"Your energy continues to return.",
"Today may feel more open and steady.",
"You deserve recognition for your strength.",
"The cycle is closing with balance.",
"Your body is restoring its natural pace.",
"You are entering a fresh stage.",
"Move forward gently and confidently.",
"Your strength has carried you through.",
"Energy may continue rising today.",
"You deserve appreciation for your care.",
"Today may feel like a new beginning.",
"Your body has completed its work.",
"You are stepping into renewed balance.",
"Strength returns quietly.",
"Your energy is rebuilding steadily.",
"You deserve calm and comfort today.",
"The cycle moves toward completion.",
"You have handled this phase well.",
"Your body is restoring strength.",
"Today may bring clarity and lightness.",
"You deserve patience and pride.",
"Energy may feel stronger today.",
"You are moving into a refreshed state.",
"Your body has done important work.",
"You deserve kindness and rest.",
"Today may feel balanced and steady.",
"Your resilience carried you through.",
"You are stepping into renewed energy.",
"Your body continues restoring balance.",
"Move through today with quiet confidence.",
"You deserve appreciation for your strength.",
"Energy is returning naturally.",
"Today may feel like a gentle restart."
]
}
}

export const eveningMessages = {
exhausted: [
"You carried a lot today. Rest now.",
"The day is finished. Your mind can slow down.",
"Being tired means you gave effort today.",
"Let the weight of the day fall away.",
"You made it through today. That is enough.",
"Your body deserves rest tonight.",
"The workday is over. Breathe deeply.",
"Let your shoulders relax now.",
"Today asked a lot from you.",
"You showed strength by continuing.",
"The day is complete. Release it.",
"Your mind can rest now.",
"You deserve quiet tonight.",
"The hardest part of today is over.",
"You handled the day as best you could.",
"Let your thoughts settle tonight.",
"You made it to the evening.",
"Your effort today mattered.",
"Tonight belongs to rest.",
"You deserve calm after the day you had.",
"Let your mind breathe.",
"You carried the day with strength.",
"The pressure of the day can fade now.",
"You survived another demanding day.",
"Your work is done for today.",
"You deserve peace tonight.",
"Even difficult days end.",
"You have reached the moment of rest.",
"Let the day dissolve behind you.",
"You gave the day your energy.",
"The night is for recovery.",
"Your effort deserves recognition.",
"Rest your thoughts tonight.",
"You handled what you could.",
"The day has let go of you.",
"You deserve comfort and quiet.",
"Let calm replace the stress.",
"You are allowed to be tired.",
"The evening welcomes you.",
"You have done enough today.",
"Tonight asks nothing more from you.",
"You carried responsibility today.",
"The day is complete.",
"Let the noise of work fade away.",
"You deserve to slow down now.",
"You have reached the end of the day.",
"Rest is the next step.",
"The evening is your space to recover.",
"You made it through the day.",
"You deserve stillness tonight.",
"The day has finished asking things from you.",
"You handled today with strength.",
"The work is behind you now.",
"Tonight is for breathing again.",
"You can release the tension now.",
"You reached the finish of the day.",
"Your mind deserves quiet.",
"You gave today your effort.",
"The night can hold your rest.",
"You deserve gentleness tonight.",
"You carried the day forward.",
"Now let your mind rest.",
"You have reached the calm part of the day.",
"Let the tension melt away.",
"You deserve recovery.",
"You worked hard today.",
"The evening is for peace.",
"Your strength carried you here.",
"The day is complete now.",
"You deserve rest without guilt.",
"The night can restore your energy.",
"You handled a demanding day.",
"You deserve calm and quiet.",
"The weight of the day can fall away.",
"You made it through another day.",
"Rest begins here.",
"You gave the day your effort.",
"The mind deserves sleep and calm.",
"Tonight is a place for recovery.",
"You handled the day bravely.",
"The day has reached its end.",
"Your strength carried you through.",
"Now let your body relax.",
"You deserve peace tonight.",
"The evening belongs to you.",
"You have reached the moment of rest.",
"The day no longer needs you.",
"Your effort today mattered.",
"Let your thoughts drift away.",
"You deserve quiet comfort.",
"The day is finally finished.",
"You handled today with resilience.",
"The night invites you to rest.",
"You have done enough today.",
"The evening can hold your calm.",
"You deserve gentle rest tonight.",
"You reached the end of the day.",
"Let your mind release the stress.",
"You made it through today."
],

normal: [
"Today moved forward quietly.",
"A steady day is still progress.",
"You carried the day well.",
"Ordinary days build strong lives.",
"Today had its small victories.",
"The day moved forward step by step.",
"You handled what came your way.",
"Calm days still matter.",
"You showed up and that counts.",
"Another day of quiet progress.",
"Life moves forward through days like this.",
"You kept the rhythm of the day.",
"Small efforts build big futures.",
"You handled the day steadily.",
"The day passed with quiet effort.",
"Steady work is powerful.",
"You moved through today with patience.",
"Normal days still shape your story.",
"Consistency builds strength.",
"You did what needed to be done.",
"The day moved gently forward.",
"Even simple days have value.",
"You stayed steady today.",
"Progress does not always look dramatic.",
"The day unfolded naturally.",
"You carried today calmly.",
"Ordinary effort still matters.",
"You kept things moving forward.",
"The day found its balance.",
"Your presence today mattered.",
"You handled the rhythm of the day.",
"A normal day still builds tomorrow.",
"Quiet effort shapes the future.",
"You stayed present through the day.",
"The day moved forward step by step.",
"Even steady days require strength.",
"You did enough today.",
"Normal days are part of meaningful lives.",
"You carried the responsibilities of today.",
"The day progressed naturally.",
"You stayed patient through the day.",
"Your effort was real today.",
"The rhythm of work continued.",
"You moved through the hours steadily.",
"Small moments built this day.",
"Consistency is powerful.",
"You stayed grounded today.",
"The day reached its quiet ending.",
"You handled today calmly.",
"Steady days still build momentum.",
"You moved forward quietly.",
"The day carried its own rhythm.",
"You showed resilience today.",
"Even simple progress counts.",
"The day flowed forward.",
"You stayed steady through the hours.",
"A calm day still matters.",
"You moved through the day thoughtfully.",
"The day brought quiet growth.",
"You handled things well.",
"Your effort carried the day.",
"You stayed balanced today.",
"The day was another step forward.",
"Steady days build strong futures.",
"You gave today your attention.",
"The day unfolded with patience.",
"You kept the day moving.",
"Your quiet effort matters.",
"The rhythm of life continued today.",
"You handled today with calm strength.",
"The day moved gently forward.",
"Small actions created this day.",
"You showed quiet discipline.",
"The day reached its closing moment.",
"You stayed consistent today.",
"The work of the day is done.",
"You handled the normal flow of life.",
"The day completed its journey.",
"You moved through the day responsibly.",
"Ordinary days are still meaningful.",
"You stayed present today.",
"The day built your future quietly.",
"You handled the tasks of today.",
"Steady effort carried the day.",
"You stayed calm through the hours.",
"The day moved forward naturally.",
"You carried the rhythm of life today.",
"Even calm days require strength.",
"You stayed grounded through today.",
"The day closes peacefully.",
"You handled the day with patience.",
"Quiet persistence matters.",
"You stayed steady today.",
"The day has reached its end.",
"Another day of life lived fully.",
"You handled today with quiet resilience.",
"The evening welcomes your rest.",
"You carried the day forward.",
"Tonight belongs to rest.",
"The day ends calmly."
],

productive: [
"You used your energy well today.",
"Today moved forward with purpose.",
"You made meaningful progress today.",
"Your effort created real results today.",
"You handled your responsibilities well.",
"Today showed your capability.",
"Your focus carried you through the day.",
"You moved your goals forward today.",
"You used your time wisely today.",
"You gave the day your best effort.",
"Your work today made a difference.",
"You turned effort into progress.",
"Today reflected your discipline.",
"You accomplished important things today.",
"Your focus helped shape this day.",
"You handled challenges with determination.",
"You moved forward with strength today.",
"Today showed what consistent effort can do.",
"You made real progress today.",
"Your productivity deserves recognition.",
"You used your skills effectively today.",
"You handled the day with clarity.",
"You stayed focused and it paid off.",
"You moved things forward today.",
"Your effort turned plans into action.",
"You used your time with intention.",
"You worked with purpose today.",
"You achieved more than you realize.",
"Today was a step forward.",
"You stayed committed to your goals.",
"Your work today has value.",
"You handled the day with determination.",
"Your focus helped you succeed today.",
"You used your energy wisely.",
"You stayed disciplined today.",
"You pushed important work forward.",
"You gave today strong effort.",
"You turned effort into accomplishment.",
"You handled the day confidently.",
"Your progress today matters.",
"You used your abilities well today.",
"You worked with clear intention.",
"You handled your responsibilities strongly.",
"You stayed productive and focused.",
"You turned the day into progress.",
"Your effort today built momentum.",
"You worked steadily and effectively.",
"You showed determination today.",
"You moved closer to your goals.",
"You turned focus into results.",
"You worked through the day with clarity.",
"You created progress today.",
"You used your strength well today.",
"You handled your tasks with skill.",
"You made today count.",
"You used your focus wisely.",
"You built something valuable today.",
"You stayed productive through the day.",
"You showed dedication today.",
"You moved things forward successfully.",
"You stayed determined throughout the day.",
"You handled your work well.",
"You turned time into progress.",
"You stayed committed to your work.",
"You used your skills effectively.",
"You handled challenges with focus.",
"You worked with discipline today.",
"You showed strong commitment.",
"You used your energy well today.",
"You kept moving forward.",
"You handled your tasks with care.",
"You turned effort into growth.",
"You stayed consistent and productive.",
"You handled today with capability.",
"You made real progress.",
"You used your abilities wisely.",
"You handled the day with strength.",
"You worked toward your goals.",
"You kept the momentum going.",
"You showed your dedication.",
"You turned work into progress.",
"You handled the day with skill.",
"You moved forward with purpose.",
"You used your time effectively.",
"You handled responsibilities confidently.",
"You worked with determination.",
"You built momentum today.",
"You stayed productive through the day.",
"You moved forward steadily.",
"You turned effort into achievement.",
"You handled today successfully.",
"You gave the day meaningful effort.",
"You worked with clarity and focus.",
"You showed your capability today.",
"You made today productive.",
"You stayed disciplined and focused.",
"You used your strength well.",
"You made real progress today."
],

heavy: [
"Some days carry more weight than others.",
"You handled a heavy day with courage.",
"It is okay that today felt difficult.",
"Emotional days require strength too.",
"You carried a lot inside today.",
"The day may have been heavy, but it has ended.",
"You are allowed to feel everything you felt today.",
"Your emotions are valid.",
"You made it through a hard day.",
"Heavy days still move forward.",
"You gave your emotional energy today.",
"Sometimes surviving the day is enough.",
"You carried your feelings through today.",
"The day asked a lot from your heart.",
"You showed quiet resilience today.",
"It is okay to feel tired emotionally.",
"Heavy days eventually pass.",
"You handled today the best you could.",
"Your emotions deserve understanding.",
"You stayed present even when things felt hard.",
"The day may have been heavy, but you are still here.",
"Some days simply ask more from us.",
"You showed emotional strength today.",
"Today may have been difficult, but it is over now.",
"You carried more than others could see.",
"Your feelings matter.",
"You made it through a complicated day.",
"Emotional weight is still real effort.",
"You deserve gentleness tonight.",
"The day may have felt long and heavy.",
"You handled your feelings bravely.",
"It is okay that today felt difficult.",
"You gave the day your emotional strength.",
"Some days are meant for surviving.",
"You stayed standing through the weight of today.",
"You handled a lot inside today.",
"You deserve rest after such a day.",
"You carried your emotions with courage.",
"Heavy days remind us how strong we are.",
"You made it to the evening.",
"Your heart worked hard today.",
"You deserve kindness tonight.",
"The weight of the day can slowly fade.",
"You handled the emotional storm today.",
"You gave your strength to the day.",
"You deserve quiet tonight.",
"You made it through the heaviness.",
"The day may have felt overwhelming.",
"Your emotions deserve compassion.",
"You stayed strong even when it was hard.",
"Heavy days do not define you.",
"You handled today with resilience.",
"You deserve calm after today.",
"The emotional weight of today can rest now.",
"You showed strength by continuing.",
"You carried more than people saw.",
"You deserve space to breathe tonight.",
"You moved through a difficult day.",
"Your feelings matter.",
"You handled the heaviness bravely.",
"The day has ended. Let your mind rest.",
"You survived the emotional weight.",
"You deserve understanding tonight.",
"You handled what today brought.",
"The emotional effort you gave matters.",
"You stayed present through a hard day.",
"You deserve patience with yourself.",
"The day asked a lot from your heart.",
"You made it through.",
"You carried the day with quiet courage.",
"Your emotions are part of being human.",
"You deserve rest tonight.",
"The heaviness can slowly lift now.",
"You handled today with resilience.",
"You stayed strong even when it hurt.",
"You deserve compassion tonight.",
"You gave today your emotional strength.",
"Heavy days eventually become memories.",
"You are stronger than this moment.",
"You handled today bravely.",
"You deserve quiet comfort tonight.",
"You stayed standing through the storm.",
"You carried the emotional weight.",
"You deserve to release the day.",
"You made it through a hard day.",
"You handled today with strength.",
"You deserve gentleness tonight.",
"You moved through a difficult day.",
"You stayed resilient.",
"You carried your feelings with courage.",
"You deserve rest and kindness.",
"The day has ended and you made it here.",
"You handled the emotional weight.",
"You deserve understanding.",
"You made it through the heaviness.",
"Tonight can hold your rest."
],

survived: [
"You made it through today, and that matters.",
"Some days survival is the real victory.",
"You stayed standing through the day.",
"You made it to the evening.",
"Today was not easy, but you endured it.",
"You reached the end of the day.",
"You made it through one more day.",
"Surviving today was enough.",
"You handled the day the best you could.",
"You made it through the storm of today.",
"You stayed here, and that matters.",
"You got through the day step by step.",
"Today tested you, but you made it.",
"You made it to this moment.",
"You survived the day with courage.",
"You endured everything today asked of you.",
"You stayed strong enough to continue.",
"You made it through another chapter of the day.",
"You held on through today.",
"You are still standing tonight.",
"You survived another difficult day.",
"You stayed present through the hours.",
"You reached the evening with strength.",
"You carried yourself through today.",
"You handled what today brought.",
"You made it through the weight of the day.",
"You survived what the day gave you.",
"You stayed resilient today.",
"You endured the challenges of today.",
"You are here at the end of the day.",
"You got through today piece by piece.",
"You survived the pressure of today.",
"You stayed strong enough to continue.",
"You made it to the quiet of evening.",
"You endured today's difficulties.",
"You handled the day step by step.",
"You made it through with determination.",
"You survived what felt overwhelming.",
"You kept moving even when it was hard.",
"You made it through the hours.",
"You endured today's struggles.",
"You stayed resilient through today.",
"You reached the end of the day with strength.",
"You got through the day the best you could.",
"You stayed here through everything today.",
"You survived the weight of the day.",
"You handled today with resilience.",
"You kept going even when it felt heavy.",
"You made it through another tough day.",
"You endured what today brought.",
"You stayed strong enough to finish the day.",
"You survived the chaos of today.",
"You carried yourself through the hours.",
"You made it through the day step by step.",
"You endured the pressure of today.",
"You stayed standing through everything.",
"You reached the end of another day.",
"You survived what today asked from you.",
"You stayed resilient in difficult moments.",
"You got through the day one moment at a time.",
"You endured everything today offered.",
"You kept moving forward.",
"You stayed present through a hard day.",
"You survived the emotional weight of today.",
"You made it through despite the difficulty.",
"You endured the challenges that appeared.",
"You stayed here until the end of the day.",
"You got through the hours.",
"You survived today's storms.",
"You handled the day with quiet strength.",
"You endured what today demanded.",
"You stayed resilient until evening.",
"You made it through the pressure of today.",
"You carried yourself through difficult moments.",
"You survived the unexpected parts of today.",
"You endured today's obstacles.",
"You made it to this calm moment.",
"You stayed present through the day.",
"You survived the challenges that came.",
"You got through today slowly but surely.",
"You endured everything today brought.",
"You stayed strong through the hours.",
"You survived the weight of responsibility.",
"You made it through the day one step at a time.",
"You endured today's difficult moments.",
"You stayed resilient until the end.",
"You got through today with courage.",
"You survived the pressure and the stress.",
"You handled what you could today.",
"You endured the demands of the day.",
"You stayed strong enough to reach tonight.",
"You made it through everything today asked.",
"You survived and that is meaningful.",
"You endured another day of life.",
"You stayed resilient through it all.",
"You reached the evening and that matters.",
"You made it through."
]
}